In [1]:
a=[]


In [2]:
a[3]=1

IndexError: list assignment index out of range

In [4]:
c= [1, 2, 'hello', [10,20]]
print(c)

[1, 2, 'hello', [10, 20]]


In [5]:
a = [10, 20, 30, [40, 50]]
print(a)

[10, 20, 30, [40, 50]]


In [6]:
a[3][0]

40

In [8]:
a.append(80)
a

[10, 20, 30, [40, 50], 80, 80]

In [9]:
 
a

[10, 20, 30, [40, 50], 80, 80, [70, 50]]

In [10]:
a.sort()

TypeError: '<' not supported between instances of 'list' and 'int'

In [11]:
a.pop()

[70, 50]

In [12]:
a

[10, 20, 30, [40, 50], 80, 80]

In [13]:
a.pop(1)

20

In [17]:
a

[10, 30, 80, 80]

In [18]:
a.remove(80)

In [19]:
a.index(80)

2

In [21]:
menu = {'김밥' : 2000, '라면': 3000, '돈까스' : 50000}
print(menu)

{'김밥': 2000, '라면': 3000, '돈까스': 50000}


In [25]:
menu['떡볶이'] =3000

In [27]:
print(menu)

{'김밥': 2000, '라면': 3000, '돈까스': 50000, '떡볶이': 3000}


In [28]:
menu.items()

dict_items([('김밥', 2000), ('라면', 3000), ('돈까스', 50000), ('떡볶이', 3000)])

In [29]:
menu.values()

dict_values([2000, 3000, 50000, 3000])

In [30]:
menu.keys()

dict_keys(['김밥', '라면', '돈까스', '떡볶이'])

In [31]:
import re

In [32]:
re.match('Hello', 'Hello, World')

<re.Match object; span=(0, 5), match='Hello'>

In [37]:
re.match('ab[0-9]?d', 'ab3d')

<re.Match object; span=(0, 4), match='ab3d'>

In [39]:
re.match('(hello){3}', 'hellohellohelloworld')

<re.Match object; span=(0, 15), match='hellohellohello'>

In [45]:
re.match('a*', 'tewrdbbaa')

<re.Match object; span=(0, 0), match=''>

In [46]:
import numpy as np

In [49]:
arr1 = np.array([1,2,3,4,5])

In [50]:
print(arr1)

[1 2 3 4 5]


In [51]:
type(arr1)

numpy.ndarray

In [53]:
arr2 = np.array([[1,2,3], [4,5,6]])

In [54]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr3 =([[[1,2,3,], [4,5,6], [7,8,9]],
        [[1,2,3], [4,5,6,], [7,8,9]],
        [[1,2,3,],[4,5,6], [7,8,9]]])
        
arr3

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [57]:
a= np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
b=np.ones((3,3,3,3))
b

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [61]:
a = np.full((3,3), 1.5)
print(a)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [63]:
a = np.eye(3,3,3)
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
a= np.arange(1, 21, 5)
a

array([ 1,  6, 11, 16])

In [66]:
a = np.linspace(0, 10 ,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [67]:
a= np.random.random()
a

0.8436199843781277

In [69]:
a= np.random.random((4,4))
a

array([[0.5341624 , 0.65948569, 0.2620645 , 0.44512004],
       [0.90241069, 0.56403598, 0.57039785, 0.28546239],
       [0.60157638, 0.57318859, 0.2340976 , 0.68690582],
       [0.11557534, 0.73873949, 0.29123231, 0.32549703]])

In [70]:
a= np.random.randint(1, 10, (4,4))
a

array([[5, 8, 5, 1],
       [1, 8, 7, 3],
       [1, 6, 9, 9],
       [6, 5, 3, 9]])

In [71]:
a = np.random.rand(3,3)
a

array([[0.1887438 , 0.19893476, 0.34830037],
       [0.65218951, 0.20664344, 0.40538084],
       [0.2798197 , 0.69574941, 0.43838307]])

In [72]:
a = np.random.randn(3,3)
a

array([[ 2.28204763e-01,  2.11011733e-01, -8.06415785e-01],
       [ 2.84073585e+00,  1.77772260e-03, -3.37844966e-01],
       [-8.50747499e-01, -1.34576019e-01,  1.80726855e+00]])

In [76]:
arr = np.arange(1, 9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
arr.ndim

1

In [77]:
arr .shape

(8,)

In [78]:
arr.dtype

dtype('int32')

In [79]:
arr.intersize

AttributeError: 'numpy.ndarray' object has no attribute 'intersize'

In [80]:
arr.itersize

AttributeError: 'numpy.ndarray' object has no attribute 'itersize'

In [81]:
arr.itrnsize

AttributeError: 'numpy.ndarray' object has no attribute 'itrnsize'

In [82]:
arr.size

8

In [83]:
arr.itemsize

4

In [84]:
arr.dtype

dtype('int32')

In [85]:
arr.nbytes

32

In [86]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
arr.ndim

1

In [88]:
arr2.ndim


2

In [89]:
arr2.shape

(2, 3)

In [90]:
arr2.size

6

In [91]:
arr2.dtype

dtype('int32')

In [92]:
arr2.itemzie

AttributeError: 'numpy.ndarray' object has no attribute 'itemzie'

In [93]:
arr2.itemsize

4

In [94]:
arr2.nbytes

24

In [95]:
arr2d = np.arange(9).reshape((3,3))
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
arr2d[0,1]

1

In [97]:
arr[-2:]

array([7, 8])

In [98]:
a2= np.arange(1,25).reshape((4,6))
a2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [99]:
a2[1]

array([ 7,  8,  9, 10, 11, 12])

In [100]:
a2[1:3, 1:5]

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])

In [101]:
a2[1, :]

array([ 7,  8,  9, 10, 11, 12])

In [102]:
a2[:,1]

array([ 2,  8, 14, 20])

In [103]:
a2[-1,:]

array([19, 20, 21, 22, 23, 24])

In [104]:
a2[::-1, ::-1]

array([[24, 23, 22, 21, 20, 19],
       [18, 17, 16, 15, 14, 13],
       [12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1]])

In [105]:
a2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [107]:
a= np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
a <5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [109]:
a[a <5]

array([0, 1, 2, 3, 4])

In [110]:
a[a%2 ==0]

array([ 0,  2,  4,  6,  8, 10])

In [111]:
a[(a>5) & (a <11)]

array([ 6,  7,  8,  9, 10])

In [112]:
a[(a >9) | (a <5)]

array([ 0,  1,  2,  3,  4, 10])

In [113]:
a[~(a%3==0)]

array([ 1,  2,  4,  5,  7,  8, 10])